---

stages:
  - check
  - test
  - cover
  - publish

.before_script: &pkgs_dependent_cc
  - apt update
  - apt install -y build-essential

cargo check:
  image: containers.dev.maio.me/sjohnson/containers/rust:latest
  stage: check
  tags:
    - amd64
  before_script: *pkgs_dependent_cc
  script:
    - cargo clean
    - cargo check
  cache:
    policy: push
    paths:
      - target

cargo tests amd64:
  image: containers.dev.maio.me/sjohnson/containers/rust:latest
  stage: test
  tags:
    - amd64
  before_script: *pkgs_dependent_cc
  script:
    - cargo test
  cache:
    paths:
      - target
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip[-_ ]tests\]/i

kcov cover amd64:
  image: containers.dev.maio.me/sjohnson/containers/kcov:latest
  stage: cover
  tags:
    - amd64
  dependencies:
    - cargo tests amd64
  script:
    - mkdir -p ./coverage/units ./coverage/doctest
    - "find ./target/debug -maxdepth 1 -regex '.*_test-[^.]*$' | xargs -n1 /app/bin/kcov --collect-only ./coverage/units"
    - "find ./target/debug -maxdepth 1 -regex '.*rust_pca9685-[^.]*$' | xargs -n1 /app/bin/kcov --collect-only ./coverage/doctest"
    - kcov --merge ./coverage ./coverage/units ./coverage/doctest
  cache:
    policy: pull
    paths:
      - target
  artifacts:
    name: coverage
    paths:
      - coverage

pages:
  image: containers.dev.maio.me/sjohnson/containers/rust:latest
  stage: publish
  tags:
    - amd64
  before_script: *pkgs_dependent_cc
  dependencies:
    - kcov cover amd64
  script:
    - cargo doc --target-dir . --no-deps --lib
    - mv doc public
    - mv coverage public/coverage
    - cp -v ci/docs/index.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
